name: 🚀 feature request
description: Create a request for a new feature
labels: [enhancement]
body:
  - type: textarea
    id: new_feature
    attributes:
      label: New Feature
      description: Explain what the new feature is supposed to do.
    validations:
      required: true
  - type: textarea
    id: feature_example
    attributes:
      label: Feature Example
      description: Please give an example if available
    validations:
      required: false
